### ISSUE TITLE
missing pyproject.toml and missing on publish PyPI for pipx compatiblety

### ISSUE THREAD

**Issue by MaxPeal** [recrm/ArchiveTools#10]
please add a pyproject.toml and publish all to PyPI for pipx compatiblety
and add a [console scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) entry point. If you're a poetry user, use [these instructions](https://python-poetry.org/docs/pyproject/#scripts).

**Comment by recrm** [comment]
Resolved. I've added warc-extractor to pip in the most recent commit. See comments in readme.
