### ISSUE TITLE
DeprecationWarning on import of MutableMapping

### ISSUE THREAD

**Issue by kaosengr** [recrm/ArchiveTools#6]
warc-extractor.py:38: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping

change line 38 of warc-extractor.py:

from collections import MutableMapping

to

from collections.abc import MutableMapping

**Comment by recrm** [comment]
Yea this is an issue. Thanks for pointing it out. I've been meaning to do some maintenance on this repository for a while. I guess this will give me the excuse I need.

**Comment by recrm** [comment]
Fixed
